//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChineseT2S.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChineseT2S.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 锕,錒|锿,鎄|皑,皚|嗳,噯|蔼,藹|霭,靄|爱,愛|嫒,嬡|碍,礙|暧,曖|瑷,璦|庵,菴|谙,諳|鹌,鵪|鞍,鞌|埯,垵|铵,銨|暗,闇|暗,晻|翱,翶|翱,翺|鳌,鰲|鳌,鼇|袄,襖|媪,媼|岙,嶴|奥,奧|骜,驁|钯,鈀|坝,垻|坝,壩|罢,罷|鲅,鮁|霸,覇|摆,擺|呗,唄|败,敗|稗,粺|颁,頒|坂,岅|板,闆|钣,鈑|办,辦|绊,絆|帮,幫|绑,綁|榜,牓|膀,艕|谤,謗|镑,鎊|龅,齙|褒,裦|宝,寶|饱,飽|鸨,鴇|褓,緥|报,報|鲍,鮑|杯,盃|杯,桮|鹎,鵯|贝,貝|狈,狽|备,備|背,揹|钡,鋇|悖,誖|惫,憊|辈,輩|鞴,韝|奔,逩|奔,犇|贲,賁|锛,錛|绷,綳|绷,繃|逼,偪|秕,粃|笔,筆|币,幣|毕,畢|闭,閉|哔,嗶|荜,蓽|毙,斃|铋,鉍|筚,篳|滗,潷|痹,痺|跸,蹕|辟,闢|弊,獘|边,邊|笾,籩|编,編|鳊,鯿|贬,貶|变,變|缏,緶|辩,辯|辫,辮|标,標|飑,颮|骠,驃|膘,臕|镖,鏢|飙,飆|飙,飇|飚,飈|镳,鑣|表,錶|鳔,鰾|鳖,鱉|鳖,鼈|别,別|别,彆|瘪,癟|宾,賓|宾,賔|傧,儐|滨,濱|缤,繽|槟,檳|镔,鑌|濒,瀕|摈,擯|殡,殯|膑,臏| [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string s2t {
            get {
                return ResourceManager.GetString("s2t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 庵,菴|暗,晻|暗,闇|案,桉|鞍,鞌|鳌,鼇|柏,栢|稗,粺|坂,岅|幇,幫|膀,髈|榜,牓|刨,鉋|刨,鑤|褓,緥|褒,襃|背,揹|備,俻|悖,誖|杯,桮|杯,盃|奔,犇|奔,逩|綳,繃|痹,痺|逼,偪|斃,獘|秘,祕|弊,獘|秕,粃|遍,徧|膘,臕|鳖,鼈|并,並|并,併|并,竝|冰,氷|禀,稟|鉢,缽|鉢,盋|博,愽|駁,駮|布,佈|踩,跴|采,寀|采,採|睬,倸|彩,綵|參,叅|慚,慙|操,撡|草,艸|册,冊|厠,廁|策,筴|插,揷|查,査|察,詧|鏟,剗|鏟,剷|嘗,嚐|嘗,甞|扯,撦|嗔,瞋|趁,趂|乘,乗|乘,椉|塍,堘|撑,撐|澄,澂|耻,恥|敕,勅|敕,勑|翅,翄|痴,癡|吃,喫|仇,雠|仇,讐|绸,紬|瞅,矁|酬,詶|酬,酧|酬,醻|厨,廚|蹰,躕|橱,櫉|鋤,耡|鋤,鉏|船,舩|創,剏|創,剙|床,牀|窗,牎|窗,牕|窗,窓|窗,窻|捶,搥|棰,箠|錘,鎚|蠢,惷|春,旾|淳,湻|莼,蓴|唇,脣|醇,醕|辭,辤|糍,餈|鷀,鶿|勿,怱|勿,悤|葱,蔥|凑,湊|蹴,蹵|粗,麤|粗,觕|篡,簒|脆,脃|悴,顇|村,邨|銼,剉|呆,獃|呆,騃|玳,瑇|淡,澹|啖,啗|啖,噉|耽,躭|擋,攩| [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string v2t {
            get {
                return ResourceManager.GetString("v2t", resourceCulture);
            }
        }
    }
}
